begin;
select no_plan();
select has_function('public','begin_resource_adoption',array['jsonb'],'resource adoption begins through authenticated RPC');
select is((select provolatile::text from pg_proc where oid='private.resource_adoption_result_valid(jsonb)'::regprocedure),'s','timestamp-validating receipt checker is STABLE rather than immutable');
insert into auth.users(id,email) values('fc000000-0000-4000-8000-000000000001','adoption-owner@example.test'),('fc000000-0000-4000-8000-000000000002','adoption-other@example.test');
insert into public.goals(id,owner_id,blueprint_id,title,position) select 'fc000000-0000-4000-8000-000000000010',owner_id,id,'Goal',0 from public.blueprints where owner_id='fc000000-0000-4000-8000-000000000001';
insert into public.stages(id,owner_id,goal_id,title,position) values('fc000000-0000-4000-8000-000000000011','fc000000-0000-4000-8000-000000000001','fc000000-0000-4000-8000-000000000010','Stage',0);
insert into public.path_nodes(id,owner_id,stage_id,node_type,title,position) values('fc000000-0000-4000-8000-000000000012','fc000000-0000-4000-8000-000000000001','fc000000-0000-4000-8000-000000000011','learn','Node',0);
insert into public.resource_bindings(id,owner_id,node_id,kind,url,external_id,position) values
 ('fc000000-0000-4000-8000-000000000019','fc000000-0000-4000-8000-000000000001','fc000000-0000-4000-8000-000000000012','youtube_video','https://www.youtube.com/watch?v=zzzzzzzzzzz','zzzzzzzzzzz',0),
 ('fc000000-0000-4000-8000-000000000018','fc000000-0000-4000-8000-000000000001','fc000000-0000-4000-8000-000000000012','youtube_video','https://www.youtube.com/watch?v=yyyyyyyyyyy','yyyyyyyyyyy',1);
insert into public.learning_sessions(owner_id,node_id,resource_binding_id,source,started_at,client_mutation_id) values('fc000000-0000-4000-8000-000000000001','fc000000-0000-4000-8000-000000000012','fc000000-0000-4000-8000-000000000019','extension',now(),gen_random_uuid());
create function pg_temp.aid(n integer) returns uuid language sql as $$select ('fc000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.request(n integer) returns jsonb language sql as $$select jsonb_build_object('adoptionId',pg_temp.aid(n),'sourceRunId',pg_temp.aid(21),'videoId','abcdefghijk','replaceBindingId',null)$$;
select set_config('adoption_test.verified','{"status":"verified","video":{"videoId":"abcdefghijk","title":"A useful video","channelTitle":"A channel","publishedAt":"2026-01-01T00:00:00Z","durationSeconds":900}}',true);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"fc000000-0000-4000-8000-000000000001"}',true);
select set_config('adoption_test.snapshot',public.read_blueprint_snapshot_v2(auth.uid())::text,true);
reset role;
-- Existing trusted pipeline records are context fixtures, not substitutes for the adoption RPCs.
insert into public.resource_runs(id,owner_id,blueprint_id,blueprint_version,node_id,kind,preferences,learner_context,input_blueprint,result,status,expires_at)
 select pg_temp.aid(20),owner_id,id,version,pg_temp.aid(12),'discover','{}','{}',current_setting('adoption_test.snapshot')::jsonb,
 '{"status":"discovered","candidates":[{"video":{"videoId":"abcdefghijk"},"eligibleForMatching":true,"transcript":{"status":"ready"}},{"video":{"videoId":"lmnopqrstuv"},"eligibleForMatching":true,"transcript":{"status":"ready"}}]}','ready',clock_timestamp()+interval '120 seconds' from public.blueprints where owner_id=pg_temp.aid(1);
insert into public.resource_runs(id,owner_id,blueprint_id,blueprint_version,node_id,kind,source_run_id,preferences,learner_context,input_blueprint,input_discovery,result,status,expires_at)
 select pg_temp.aid(21),owner_id,blueprint_id,blueprint_version,node_id,'match',id,preferences,learner_context,input_blueprint,result,
 '{"status":"matched","assessments":[{"videoId":"abcdefghijk","role":"recommended"},{"videoId":"lmnopqrstuv","role":"alternative"}]}','ready',expires_at from public.resource_runs where id=pg_temp.aid(20);
set local role authenticated;
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(30)||'{"draft":{}}')$$,'22023','RESOURCE_ADOPTION_INVALID','caller cannot supply a draft');
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(30))$$,'P0001','RESOURCE_ADOPTION_QUOTA_EXHAUSTED','missing quota means zero');
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(30)||'{"videoId":"xxxxxxxxxxx"}')$$,'40001','RESOURCE_ADOPTION_SOURCE_CHANGED','unassessed video is not selectable');
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(30)||jsonb_build_object('replaceBindingId',pg_temp.aid(999)))$$,'22023','RESOURCE_ADOPTION_INVALID','replacement belongs to current selected node');
reset role;
insert into private.resource_adoption_quotas values(pg_temp.aid(1),30);
set local role authenticated;
select is(public.begin_resource_adoption(pg_temp.request(30))->>'status','queued','begin reserves a verification without applying');
select is(public.begin_resource_adoption(pg_temp.request(30))->>'node_id',pg_temp.aid(12)::text,'node is derived from stored source');
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(30)||'{"videoId":"lmnopqrstuv"}')$$,'22023','RESOURCE_ADOPTION_RUN_REUSED','same identity cannot change selected video');
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(31))$$,'P0001','RESOURCE_ADOPTION_BUSY','one active verification per account');
select throws_ok($$update public.resource_adoptions set status='failed'$$,'42501',null,'browser cannot self-attest verification');
select throws_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30))$$,'42501',null,'browser cannot claim service work');
reset role;
select is((select available_attempts from private.resource_adoption_quotas where owner_id=pg_temp.aid(1)),29,'exact begin replay charges once');
set local role service_role;
select is(public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30))->'acquired','true'::jsonb,'first claim acquires');
select is(public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(31))->'acquired','false'::jsonb,'repeat claim never acquires another call');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(31),current_setting('adoption_test.verified')::jsonb)$$,'42501','RESOURCE_ADOPTION_FORBIDDEN','wrong lease cannot finish');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30),jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,videoId}','"lmnopqrstuv"'))$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','receipt must match selected video');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30),current_setting('adoption_test.verified')::jsonb||'{"extra":true}')$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','receipt rejects extra fields');
select is(public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30),current_setting('adoption_test.verified')::jsonb)->>'status','ready','verified result creates reviewable proposal');
select set_config('adoption_test.receipt',public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30),current_setting('adoption_test.verified')::jsonb)::text,true);
select is(public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30),current_setting('adoption_test.verified')::jsonb),current_setting('adoption_test.receipt')::jsonb,'exact finish recovers same row');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(30),pg_temp.aid(30),'{"status":"changed"}')$$,'22023','RESOURCE_ADOPTION_COMPLETION_REUSED','changed receipt cannot overwrite result');
reset role;
select is((select count(*) from public.blueprint_proposals where owner_id=pg_temp.aid(1)),1::bigint,'finish retries create exactly one proposal');
select is((select valid_until-verified_at from public.resource_adoptions where id=pg_temp.aid(30)),interval '10 minutes','database verification lasts ten minutes');
set local role authenticated;
select set_config('adoption_test.proposal',current_setting('adoption_test.receipt')::jsonb->>'proposal_id',true);
select is(public.read_blueprint_snapshot_v2(auth.uid()),current_setting('adoption_test.snapshot')::jsonb,'verification leaves formal graph unchanged');
select is_empty($$update public.blueprint_proposals set proposed_snapshot='{}',status='rejected' where id=current_setting('adoption_test.proposal')::uuid returning id$$,'associated proposal cannot be rewritten');
select throws_ok($$select private.apply_blueprint_proposal_pre_adoption(current_setting('adoption_test.proposal')::uuid,0,pg_temp.aid(30))$$,'42501',null,'legacy guard is not a bypass');
reset role;
update public.blueprint_proposals set proposed_snapshot=jsonb_set(proposed_snapshot,'{title}','"Forged"') where id=current_setting('adoption_test.proposal')::uuid;
set local role authenticated;
select throws_ok($$select public.apply_blueprint_proposal(current_setting('adoption_test.proposal')::uuid,0,pg_temp.aid(30))$$,'23514','RESOURCE_ADOPTION_PROPOSAL_INVALID','final public guard checks complete immutable draft');
reset role;
update public.blueprint_proposals p set proposed_snapshot=private.resource_adoption_draft(a) from public.resource_adoptions a where p.id=a.proposal_id and a.id=pg_temp.aid(30);
set local role authenticated;
select is(public.apply_blueprint_proposal(current_setting('adoption_test.proposal')::uuid,0,pg_temp.aid(30)),1::bigint,'explicit confirmation applies version one');
select is(public.read_resource_adoption(pg_temp.aid(30))->>'status','applied','formal application updates adoption receipt');
select is(public.read_blueprint_snapshot_v2(auth.uid())#>>'{goals,0,stages,0,nodes,0,resources,0,externalId}','zzzzzzzzzzz','append preserves first resource order despite UUID ordering');
select is(public.read_blueprint_snapshot_v2(auth.uid())#>>'{goals,0,stages,0,nodes,0,resources,1,externalId}','yyyyyyyyyyy','append preserves second resource order');
select is(public.read_blueprint_snapshot_v2(auth.uid())#>>'{goals,0,stages,0,nodes,0,resources,2,externalId}','abcdefghijk','selected canonical binding is appended');
select is(public.read_blueprint_snapshot_v2(auth.uid()),(select snapshot from public.blueprint_revisions where proposal_id=current_setting('adoption_test.proposal')::uuid),'formal snapshot and immutable revision agree exactly');
select throws_ok($$select public.reject_resource_adoption(pg_temp.aid(30))$$,'23514','PROPOSAL_NOT_PENDING','applied adoption cannot be rejected');
reset role;
update public.resource_adoptions set valid_until=clock_timestamp()-interval '1 second' where id=pg_temp.aid(30);
update public.blueprints set version=2 where owner_id=pg_temp.aid(1);
set local role authenticated;
select is(public.apply_blueprint_proposal(current_setting('adoption_test.proposal')::uuid,0,pg_temp.aid(30)),1::bigint,'exact applied replay returns historical version after expiry and later edits');
select throws_ok($$select public.apply_blueprint_proposal(current_setting('adoption_test.proposal')::uuid,1,pg_temp.aid(30))$$,'40001','BLUEPRINT_VERSION_CONFLICT','replay cannot change expected version');
select throws_ok($$select public.apply_blueprint_proposal(current_setting('adoption_test.proposal')::uuid,0,pg_temp.aid(31))$$,'23514','PROPOSAL_NOT_PENDING','replay cannot change mutation');
select set_config('adoption_test.snapshot',public.read_blueprint_snapshot_v2(auth.uid())::text,true);
reset role;
-- Refresh only trusted source fixture for the next current Blueprint version.
update public.resource_runs set blueprint_version=2,input_blueprint=current_setting('adoption_test.snapshot')::jsonb where owner_id=pg_temp.aid(1);
create or replace function pg_temp.request(n integer) returns jsonb language sql as $$select jsonb_build_object('adoptionId',pg_temp.aid(n),'sourceRunId',pg_temp.aid(21),'videoId','lmnopqrstuv','replaceBindingId',pg_temp.aid(19))$$;
select set_config('adoption_test.verified',jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,videoId}','"lmnopqrstuv"')::text,true);
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(32))$$,'replacement can begin from new current source');
reset role;
set local role service_role;
select lives_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(32),pg_temp.aid(32))$$,'replacement claim');
select set_config('adoption_test.replacement',public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(32),pg_temp.aid(32),current_setting('adoption_test.verified')::jsonb)->>'proposal_id',true);
reset role;
set local role authenticated;
select is(public.apply_blueprint_proposal(current_setting('adoption_test.replacement')::uuid,2,pg_temp.aid(32)),3::bigint,'replacement confirms once');
select is(public.read_blueprint_snapshot_v2(auth.uid())#>>'{goals,0,stages,0,nodes,0,resources,0,externalId}','lmnopqrstuv','replacement occupies original slot');
select isnt(public.read_blueprint_snapshot_v2(auth.uid())#>>'{goals,0,stages,0,nodes,0,resources,0,id}',pg_temp.aid(19)::text,'replacement allocates new identity');
select is((select resource_binding_id from public.learning_sessions where owner_id=auth.uid()),pg_temp.aid(19),'past learning session stays attached to original video');
select is(public.read_blueprint_snapshot_v2(auth.uid()),(select snapshot from public.blueprint_revisions where proposal_id=current_setting('adoption_test.replacement')::uuid),'replacement formal snapshot matches revision exactly');
reset role;
select ok((select archived_at is not null from public.resource_bindings where id=pg_temp.aid(19)),'replaced binding remains archived for attribution');
select is((select external_id from public.resource_bindings where id=pg_temp.aid(19)),'zzzzzzzzzzz','past binding retains original video');
-- Use another eligible candidate for remaining lifecycle tests.
update public.resource_runs set blueprint_version=3,input_blueprint=jsonb_set(input_blueprint,'{version}','3'),
 input_discovery=replace(input_discovery::text,'lmnopqrstuv','12345678901')::jsonb,result=replace(result::text,'lmnopqrstuv','12345678901')::jsonb where owner_id=pg_temp.aid(1);
create or replace function pg_temp.request(n integer) returns jsonb language sql as $$select jsonb_build_object('adoptionId',pg_temp.aid(n),'sourceRunId',pg_temp.aid(21),'videoId','12345678901','replaceBindingId',null)$$;
select set_config('adoption_test.verified',jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,videoId}','"12345678901"')::text,true);
set local role authenticated;
select is(public.begin_resource_adoption(pg_temp.request(40))->>'status','queued','queued cancellation fixture');
select is(public.cancel_resource_adoption(pg_temp.aid(40))->>'status','cancelled','queued cancellation terminal');
select is(public.cancel_resource_adoption(pg_temp.aid(40))->>'status','cancelled','cancel retry is idempotent');
reset role;
select is((select available_attempts from private.resource_adoption_quotas where owner_id=pg_temp.aid(1)),28,'only two claimed verifications spent credit; queued cancel refunds once');
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(41))$$,'running cancellation fixture');
reset role;
set local role service_role;
select lives_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(41),pg_temp.aid(41))$$,'running cancellation claimed');
reset role;
set local role authenticated;
select is(public.cancel_resource_adoption(pg_temp.aid(41))->>'status','cancelled','cancel claimed work');
reset role;
set local role service_role;
select is(public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(41),pg_temp.aid(41),current_setting('adoption_test.verified')::jsonb)->>'status','cancelled','late success cannot revive cancelled work');
reset role;
select is((select available_attempts from private.resource_adoption_quotas where owner_id=pg_temp.aid(1)),27,'claimed cancellation never refunds potential usage');
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(42))$$,'queued expiry fixture');
reset role;
update public.resource_adoptions set expires_at=clock_timestamp()-interval '1 second' where id=pg_temp.aid(42);
set local role service_role;
select is(public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(42),pg_temp.aid(42))->'acquired','false'::jsonb,'expired queued request cannot call provider');
reset role;
select is((select available_attempts from private.resource_adoption_quotas where owner_id=pg_temp.aid(1)),27,'queued expiry refunds credit');
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(43))$$,'running expiry fixture');
reset role;
set local role service_role;
select lives_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(43),pg_temp.aid(43))$$,'running expiry claim');
reset role;
update public.resource_adoptions set expires_at=clock_timestamp()-interval '1 second' where id=pg_temp.aid(43);
set local role service_role;
select is(public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(43),pg_temp.aid(43),current_setting('adoption_test.verified')::jsonb)->>'status','interrupted','expired claimed work cannot revive');
reset role;
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(44))$$,'source change before claim fixture');
reset role;
update public.path_nodes set archived_at=clock_timestamp() where id=pg_temp.aid(12);
set local role authenticated;
select is(public.read_resource_adoption(pg_temp.aid(44))->>'status','stale','removed node invalidates queued source');
reset role;
select is((select available_attempts from private.resource_adoption_quotas where owner_id=pg_temp.aid(1)),26,'unclaimed source change refunds once');
update public.path_nodes set archived_at=null where id=pg_temp.aid(12);
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(45))$$,'source change during provider fixture');
reset role;
set local role service_role;
select lives_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(45),pg_temp.aid(45))$$,'source change during provider claim');
reset role;
update public.path_nodes set archived_at=clock_timestamp() where id=pg_temp.aid(12);
set local role service_role;
select is(public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(45),pg_temp.aid(45),current_setting('adoption_test.verified')::jsonb)->>'status','stale','finish cannot propose from removed node');
reset role;
select ok((select proposal_id is null and verified_at is null from public.resource_adoptions where id=pg_temp.aid(45)),'stale finish creates neither proposal nor current verification');
update public.path_nodes set archived_at=null where id=pg_temp.aid(12);
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(46))$$,'verification expiry fixture');
reset role;
set local role service_role;
select lives_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46))$$,'verification expiry claim');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46),jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,durationSeconds}','86401'))$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','duration is bounded');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46),jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,durationSeconds}','1.5'))$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','duration must be integer');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46),jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,title}',to_jsonb(repeat('a',501))))$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','title is bounded');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46),jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,channelTitle}','"  "'))$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','channel title is nonempty');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46),jsonb_set(current_setting('adoption_test.verified')::jsonb,'{video,publishedAt}','"2026-02-31T00:00:00Z"'))$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','published date is real calendar time');
select throws_ok($$select public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46),'{"status":"not_found","video":{}}')$$,'22023','RESOURCE_ADOPTION_INVALID_RESULT','failure receipt cannot carry arbitrary evidence');
select set_config('adoption_test.expired',public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(46),pg_temp.aid(46),current_setting('adoption_test.verified')::jsonb)->>'proposal_id',true);
reset role;
update public.resource_adoptions set valid_until=clock_timestamp()-interval '1 second' where id=pg_temp.aid(46);
set local role authenticated;
select throws_ok($$select public.apply_blueprint_proposal(current_setting('adoption_test.expired')::uuid,3,pg_temp.aid(46))$$,'40001','RESOURCE_ADOPTION_VERIFICATION_EXPIRED','generic confirmation enforces verification expiry');
select is(public.read_resource_adoption(pg_temp.aid(46))->>'status','stale','read retains expired proposal as historical');
select is(public.reject_resource_adoption(pg_temp.aid(46))->>'status','rejected','historical pending proposal can be rejected');
select is(public.reject_resource_adoption(pg_temp.aid(46))->>'status','rejected','rejection is idempotent');
select is((select status from public.blueprint_proposals where id=current_setting('adoption_test.expired')::uuid),'rejected','rejection updates proposal and adoption together');
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(47)||'{"videoId":"abcdefghijk"}')$$,'22023','RESOURCE_ADOPTION_INVALID','selected video already bound cannot be appended');
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(47))$$,'fresh verification for final source guard');
reset role;
set local role service_role;
select lives_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(47),pg_temp.aid(47))$$,'fresh verification claimed');
select set_config('adoption_test.changed',public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(47),pg_temp.aid(47),current_setting('adoption_test.verified')::jsonb)->>'proposal_id',true);
reset role;
update public.blueprints set version=4 where owner_id=pg_temp.aid(1);
set local role authenticated;
select throws_ok($$select public.apply_blueprint_proposal(current_setting('adoption_test.changed')::uuid,3,pg_temp.aid(47))$$,'40001','RESOURCE_ADOPTION_SOURCE_CHANGED','generic confirmation atomically rejects later Blueprint version');
select is(public.read_resource_adoption(pg_temp.aid(47))->>'status','stale','ready source change is reconciled without erasing proposal');
reset role;
update public.blueprints set version=3 where owner_id=pg_temp.aid(1);
insert into public.resource_bindings(id,owner_id,node_id,kind,url,external_id,position)
 select pg_temp.aid(100+n),pg_temp.aid(1),pg_temp.aid(12),'youtube_video','https://www.youtube.com/watch?v='||lpad(n::text,11,'0'),lpad(n::text,11,'0'),n+3 from generate_series(1,13) n;
set local role authenticated;
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(48))$$,'22023','RESOURCE_ADOPTION_INVALID','append enforces sixteen resource ceiling');
reset role;
delete from public.resource_bindings where id between pg_temp.aid(101) and pg_temp.aid(113);
set local role authenticated;
select lives_ok($$select public.begin_resource_adoption(pg_temp.request(48))$$,'provider failure fixture');
reset role;
set local role service_role;
select lives_ok($$select public.claim_resource_adoption(pg_temp.aid(1),pg_temp.aid(48),pg_temp.aid(48))$$,'provider failure claim');
select is(public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(48),pg_temp.aid(48),'{"status":"changed"}')->>'status','failed','changed provider metadata fails closed');
select is(public.finish_resource_adoption(pg_temp.aid(1),pg_temp.aid(48),pg_temp.aid(48),'{"status":"changed"}')->>'status','failed','lost failure response exact retry recovers receipt');
reset role;
select ok((select proposal_id is null from public.resource_adoptions where id=pg_temp.aid(48)),'failed verification cannot create proposal');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"fc000000-0000-4000-8000-000000000002"}',true);
select is_empty($$select id from public.resource_adoptions$$,'RLS hides another account history');
select throws_ok($$select public.read_resource_adoption(pg_temp.aid(30))$$,'P0002','RESOURCE_ADOPTION_NOT_FOUND','RPC hides another account receipt');
select throws_ok($$select public.begin_resource_adoption(pg_temp.request(50))$$,'P0002','RESOURCE_ADOPTION_NOT_FOUND','other user cannot adopt source');
select set_config('request.jwt.claims','{"sub":"fc000000-0000-4000-8000-000000000001","client_id":"extension"}',true);
select throws_ok($$select public.read_resource_adoption(pg_temp.aid(30))$$,'42501','RESOURCE_ADOPTION_FORBIDDEN','extension cannot use web adoption');
select is_empty($$select id from public.resource_adoptions$$,'extension has no direct adoption reads');
select set_config('request.jwt.claims','{"sub":"fc000000-0000-4000-8000-000000000001","is_anonymous":true}',true);
select throws_ok($$select public.read_resource_adoption(pg_temp.aid(30))$$,'42501','RESOURCE_ADOPTION_FORBIDDEN','anonymous Auth user cannot read');
reset role;
set local role anon;
select throws_ok($$select public.read_resource_adoption('fc000000-0000-4000-8000-000000000030')$$,'42501',null,'anon has no RPC execute');
reset role;
select ok(not has_table_privilege('service_role','public.resource_adoptions','UPDATE'),'service cannot directly alter receipt');
select ok(not has_table_privilege('authenticated','private.resource_adoption_leases','SELECT'),'leases are not exposed');
select ok(not has_table_privilege('service_role','private.resource_adoption_quotas','DELETE'),'quota administration cannot delete ledger');
select finish();
rollback;
