#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
WEB_ENV="$PROJECT_ROOT/apps/web/.env.local"
EXTENSION_ENV="$PROJECT_ROOT/apps/extension/.env.local"
STATE_ENV="$PROJECT_ROOT/.env.m1-cloud.local"
EXTENSION_ID="kipaapemlimhdkpcenelpjeccmnkninf"
EXTENSION_REDIRECT_URI="https://${EXTENSION_ID}.chromiumapp.org/oauth2"

require_value() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$name 不能为空。请重新运行向导并提供该值。"
    exit 1
  fi
}

require_pattern() {
  local name="$1" value="$2" pattern="$3" example="$4"
  if [[ ! "$value" =~ $pattern ]]; then
    warn "$name 格式无效；期望类似：$example"
    exit 1
  fi
}

run_supabase() {
  SUPABASE_ACCESS_TOKEN="$SUPABASE_ACCESS_TOKEN" \
    npx --yes supabase@2.115.0 "$@"
}

cd "$PROJECT_ROOT"
banner "Blueprint M1 cloud setup"

stage "Docker 兼容运行时"
say "本地 Supabase 和官方 pgTAP 需要 Docker 兼容运行时。"
if ! command -v docker >/dev/null 2>&1; then
  open_url "https://docs.docker.com/desktop/setup/install/mac-install/"
  step "安装并启动 Docker Desktop；也可以使用提供 docker 命令的 OrbStack 或 Colima。"
  pause "docker 命令可用后按 Enter 继续。"
fi
if ! command -v docker >/dev/null 2>&1 || ! docker info >/dev/null 2>&1; then
  warn "Docker daemon 尚不可用。启动运行时后重新运行本向导。"
  exit 1
fi
say "Docker daemon 已就绪。"

stage "本地 Supabase 与 pgTAP"
say "这一阶段只会重置仓库专属的本地 Supabase 数据库，不接触托管项目。"
if confirm "启动本地 Supabase、重置本地数据库并运行 pgTAP？"; then
  npm run supabase:start
  npm run supabase:reset
  npm run supabase:test
else
  warn "本地数据库门槛未执行；M1 不能完成验收。"
  exit 1
fi

stage "创建托管 Supabase 项目"
say "创建免费项目，并取得应用配置与 CLI 所需凭据。Personal Access Token 和数据库密码不会落盘。"
open_url "https://supabase.com/dashboard/new"
step "创建项目后，在 Project Settings → General 复制 Project Ref。"
ENV_FILE="$STATE_ENV"
ask SUPABASE_PROJECT_REF "粘贴 Project Ref："
require_value "SUPABASE_PROJECT_REF" "$SUPABASE_PROJECT_REF"
require_pattern "SUPABASE_PROJECT_REF" "$SUPABASE_PROJECT_REF" '^[a-z0-9]{20}$' "abcdefghijklmnopqrst"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api-keys"
step "复制 Project URL 和 Publishable Key。管理员密钥由 Supabase Edge Function 托管，不进入 Web。"
ENV_FILE="$WEB_ENV"
ask NEXT_PUBLIC_SUPABASE_URL "粘贴 Project URL（https://...supabase.co）："
ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "粘贴 Publishable Key："
require_value "NEXT_PUBLIC_SUPABASE_URL" "$NEXT_PUBLIC_SUPABASE_URL"
require_value "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
require_pattern "NEXT_PUBLIC_SUPABASE_URL" "$NEXT_PUBLIC_SUPABASE_URL" '^https://[^/[:space:]]+$' "https://project-ref.supabase.co"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
write_env NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID "pending-oauth-client"
ENV_FILE="$EXTENSION_ENV"
write_env WXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env WXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
write_env WXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID "pending-oauth-client"
open_url "https://supabase.com/dashboard/account/tokens"
step "生成一个只在本次向导中使用的 Personal Access Token。"
ENV_FILE="$STATE_ENV"
ask_secret SUPABASE_ACCESS_TOKEN "粘贴 Personal Access Token（不落盘）："
ask_secret SUPABASE_DB_PASSWORD "输入创建项目时设置的数据库密码（不落盘）："
require_value "SUPABASE_ACCESS_TOKEN" "$SUPABASE_ACCESS_TOKEN"
require_value "SUPABASE_DB_PASSWORD" "$SUPABASE_DB_PASSWORD"

stage "迁移托管数据库并登记邀请"
say "先链接项目和预览迁移；真正写入远端前会再次确认。"
SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" run_supabase link --project-ref "$SUPABASE_PROJECT_REF" --password "$SUPABASE_DB_PASSWORD"
SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" run_supabase db push --linked --dry-run --password "$SUPABASE_DB_PASSWORD"
if confirm "确认把仓库中的 Supabase migrations 推送到该托管项目？"; then
  SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" run_supabase db push --linked --password "$SUPABASE_DB_PASSWORD"
  SUPABASE_DB_PASSWORD="$SUPABASE_DB_PASSWORD" run_supabase test db --linked
  run_supabase functions deploy prepare-invited-login --project-ref "$SUPABASE_PROJECT_REF" --no-verify-jwt
else
  warn "远端迁移已取消，没有写入托管数据库。"
  exit 1
fi
ENV_FILE="$STATE_ENV"
ask M1_INVITED_EMAIL "输入首个受邀自测邮箱："
require_value "M1_INVITED_EMAIL" "$M1_INVITED_EMAIL"
if [[ "$M1_INVITED_EMAIL" == *"'"* ]]; then
  warn "邮箱不能包含单引号。"
  exit 1
fi
write_env M1_INVITED_EMAIL "$M1_INVITED_EMAIL"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/sql/new"
step "在 SQL Editor 执行下面这条语句："
printf "\n  insert into private.invite_allowlist (email) values ('%s')\n" "$M1_INVITED_EMAIL"
printf "  on conflict (email) do update set status = 'active', expires_at = null;\n\n"
pause "SQL 执行成功后按 Enter 继续。"

stage "部署 Vercel Web"
say "导入 Git 仓库并部署 apps/web。共享包位于 Root Directory 之外，必须允许构建读取。"
open_url "https://vercel.com/new"
step "Import 当前 Git 仓库，Root Directory 选择 apps/web。"
step "确认 Include source files outside of the Root Directory in the Build Step 已启用。"
step "在 Environment Variables 添加 WEB_ENV 中的三个值；OAuth Client ID 暂用 pending-oauth-client。"
note "需要：NEXT_PUBLIC_SUPABASE_URL、NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY、NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID。"
step "部署成功后复制 Production HTTPS Origin，不要包含末尾斜杠。"
ENV_FILE="$EXTENSION_ENV"
ask WXT_PUBLIC_WEB_ORIGIN "粘贴 Vercel Production Origin（https://...）："
WXT_PUBLIC_WEB_ORIGIN="${WXT_PUBLIC_WEB_ORIGIN%/}"
require_value "WXT_PUBLIC_WEB_ORIGIN" "$WXT_PUBLIC_WEB_ORIGIN"
require_pattern "WXT_PUBLIC_WEB_ORIGIN" "$WXT_PUBLIC_WEB_ORIGIN" '^https://[^/[:space:]]+$' "https://blueprint.example.com"
write_env WXT_PUBLIC_WEB_ORIGIN "$WXT_PUBLIC_WEB_ORIGIN"

stage "配置 Auth 与邀请登录链接"
say "托管 config.toml 不会由 db push 自动改变；请在 Dashboard 完成对应 Auth 设置。"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/url-configuration"
step "把 Site URL 设为 ${WXT_PUBLIC_WEB_ORIGIN}，并把 ${WXT_PUBLIC_WEB_ORIGIN}/** 加入 Redirect URLs。"
step "在 Authentication → Providers → Email 保持 Allow new users signing up 关闭。"
step "个人自测使用 Supabase 默认邮件服务时，受邀邮箱必须属于当前 Supabase Organization 成员。"
open_url "${WXT_PUBLIC_WEB_ORIGIN}/login"
step "请求一次性登录链接，在同一浏览器打开邮件，刷新页面、退出并再次登录，确认 Web 会话可以恢复。"
pause "邮件链接登录、退出和再次登录均成功后按 Enter 继续。"

stage "注册扩展 OAuth Public Client"
say "扩展使用固定 ID、精确回调地址和 Authorization Code + PKCE。"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/oauth-apps"
step "启用 OAuth Server；Authorization Path 设置为 /oauth/consent；保持动态客户端注册关闭。"
step "Add a new client：名称 Blueprint YouTube Companion，类型 Public。"
step "Redirect URI 必须精确填写：${EXTENSION_REDIRECT_URI}"
ENV_FILE="$WEB_ENV"
ask NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID "粘贴生成的 OAuth Client ID："
require_value "NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID" "$NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID"
require_pattern "NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID" "$NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID" '^[A-Za-z0-9._-]+$' "client-id-from-supabase"
write_env NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID "$NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID"
ENV_FILE="$EXTENSION_ENV"
write_env WXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID "$NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/sql/new"
step "在 SQL Editor 执行下面的配置语句："
printf "\n  insert into private.app_config (key, value)\n"
printf "  values ('extension_oauth_client_id', '%s')\n" "$NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID"
printf "  on conflict (key) do update set value = excluded.value, updated_at = now();\n\n"
step "回到 Vercel，把 NEXT_PUBLIC_EXTENSION_OAUTH_CLIENT_ID 替换为该 Client ID，并重新部署 Production。"
pause "Vercel 重新部署成功后按 Enter 继续。"

stage "构建并加载 WXT 扩展"
say "构建只会读取 apps/extension/.env.local 中的公开 Origin、Publishable Key 和 OAuth Client ID。"
npm run build:wxt
node scripts/check-m1-extension.mjs
open_url "chrome://extensions"
step "开启 Developer mode，选择 Load unpacked。"
step "加载目录：$PROJECT_ROOT/apps/extension/.output/chrome-mv3"
step "确认扩展 ID 显示为 ${EXTENSION_ID}。"
pause "扩展加载成功后按 Enter 继续。"

stage "执行 M1 托管验收"
say "逐条完成真实托管链路；任何一项失败都不要确认完成。"
step "Web：创建含学习、实践、检查点、复盘节点的蓝图，查看差异并确认提案。"
step "扩展：通过 Web Consent 授权，确认读取到同一蓝图和 YouTube 绑定节点。"
step "YouTube：打开已绑定视频，点击开始学习；回到 Web 确认学习会话可见。"
step "失败恢复：断网后再开始一条学习会话，确认进入待同步；联网后重试并确认只生成一条记录。"
step "隔离：使用第二个受邀测试账号，确认看不到或无法修改第一个账号的蓝图和会话。"
note "若仍使用默认邮件服务，第二个邮箱需先加入 Supabase Organization；否则先配置自有 SMTP。"
step "数据库：确认 Stage 4 的远端 pgTAP 全部通过，且扩展构建安全检查无服务端密钥。"
if ! confirm "以上邮件登录、提案、双端读取、会话回写、失败恢复和双账号隔离是否全部通过？"; then
  warn "M1 托管验收未通过；保留当前配置并记录失败项后再运行。"
  exit 1
fi
ENV_FILE="$STATE_ENV"
write_env M1_HOSTED_ACCEPTANCE_RESULT "pass"
write_env M1_HOSTED_ACCEPTANCE_AT "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
say "验收证据已写入 $STATE_ENV。请把结果交回 Codex，以更新 execution-roadmap.md。"

ENV_FILE="apps/web/.env.local, apps/extension/.env.local, and .env.m1-cloud.local"
finish
